#!/usr/bin/python

import argparse
import time
from http.server import BaseHTTPRequestHandler, HTTPServer

class Server(BaseHTTPRequestHandler):

    def __init__(self, *args, **kwargs):
        super(Server, self).__init__(*args, **kwargs)

    def do_GET(self):
        if self.path == "/reserve":
            # add a delay to simulate a slow response
            time.sleep(5)

        self.send_response(200)
        self.send_header("Content-type", "text/html")
        self.end_headers()
        self.wfile.write(b"Hello, world!")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-p", "--port", type=int, default=18080)

    args = parser.parse_args()

    server = HTTPServer(('127.0.0.1', args.port), Server)
    print(f"Starting server, listening on port {args.port}")

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass

    server.server_close()
