#!/usr/bin/python3
import argparse
import logging
import os
import subprocess
import sys
import time

LOG = logging.getLogger("envoy-test")

def run():
    logging.basicConfig(level=logging.INFO)

    parser = argparse.ArgumentParser()
    parser.add_argument("-o", "--output-dir", help="output directory where logs will be stored", required=True)
    parser.add_argument("--large-file", help="path to a large file used for testing")
    parser.add_argument("--envoy-bin", help="path to envoy binary", default="envoy-v1.23.2")
    parser.add_argument("--nginx-bin", help="path to nginx binary", default="nginx")

    args = parser.parse_args()

    test_dir = os.path.abspath(os.path.dirname(sys.argv[0]))
    output_dir = os.path.abspath(args.output_dir)

    envoy_bin = args.envoy_bin
    if not os.path.exists(envoy_bin):
        sys.exit(f"Unable to find {envoy_bin}, please set path to envoy binary using --envoy-bin option")

    front_envoy_config = os.path.join(test_dir, "front_envoy.yaml")
    back_envoy_config = os.path.join(test_dir, "back_envoy.yaml")
    nginx_config = os.path.join(test_dir, "nginx.conf")

    processes = []
    try:
        # run nginx
        nginx_proc = subprocess.Popen(
            [args.nginx_bin, "-p", output_dir, "-c", nginx_config],
            stdout=open(os.path.join(output_dir, "nginx.stdout"), "w"),
            stderr=open(os.path.join(output_dir, "nginx.stderr"), "w")
        )
        processes.append(nginx_proc)

        front_envoy_proc = subprocess.Popen(
            [   envoy_bin, 
                "-c", front_envoy_config,
                "--base-id", "1", "--component-log-level", "http2:debug"
            ],
            stdout=open(os.path.join(output_dir, "front_envoy.stdout"), "w"),
            stderr=open(os.path.join(output_dir, "front_envoy.stderr"), "w")
        )
        processes.append(front_envoy_proc)

        back_envoy_proc = subprocess.Popen(
            [   envoy_bin, 
                "-c", back_envoy_config,
                "--base-id", "2", "--component-log-level", "http2:debug"
            ],
            stdout=open(os.path.join(output_dir, "back_envoy.stdout"), "w"),
            stderr=open(os.path.join(output_dir, "back_envoy.stderr"), "w")
        )
        processes.append(back_envoy_proc)

        time.sleep(3)
        for p in processes:
            if p.poll() is not None:
                raise Exception(f"Failed to start process {p.args}: {p.returncode}")

        large_file_path = args.large_file
        if large_file_path is None:
            # create a large file for testing
            LOG.info("Create a test file")
            large_file_path = os.path.join(output_dir, "bigfile")
            subprocess.check_call(
                [
                    "dd",
                    "if=/dev/zero",
                    f"of={large_file_path}",
                    "bs=1M", "count=1000"
                ]
            )

        LOG.info("Uploading a big file")

        print("-" * 60)
        print("curl output:")
        print("")
        subprocess.call(
            f"curl -T {large_file_path} http://127.0.0.1:6080/upload/bigfile",
            stdout=sys.stdout, stderr=sys.stdout, shell=True,
        )
        print("")
        print("-" * 60)

    finally:
        for p in processes:
            LOG.info(f"Terminating {p.args}")
            p.terminate()
            time.sleep(0.1)
            p.kill()

if __name__ == "__main__":
    run()