#!/usr/bin/python3
import argparse
import os
import subprocess

def run():
    parser = argparse.ArgumentParser()
    parser.add_argument("-o", "--output-dir", help="output directory where logs will be stored")

    test_dir = os.path.dirname(sys.argv[0])

    front_envoy_config = os.path.join(test_dir, "front_envoy.yaml")
    back_envoy_config = os.path.join(test_dir, "back_envoy.yaml")
    nginx_config = os.path.join(test_dir, "nginx.yaml")


if __name__ == "__main__":
    run()